#### general settings
name: highlight_refinement
model: hallucination_GAN
use_tb_logger: true
distortion: sr
scale: 1
gpu_ids: [0,1,2,3]

#### datasets
datasets:
  train:
    name: HDRTV1K
    mode: LQGT_condition
    dataroot_LQ: ../dataset/Youtube_hdr/train_sdr_sub
    dataroot_cond: ../dataset/Youtube_hdr/train_sdr_bicx4LR_npy
    dataroot_GT: ../dataset/Youtube_hdr/train_hdr_sub
    cond_scale: 4
    use_shuffle: true
    n_workers: 8 
    batch_size: 64 
    GT_size: 128 
    use_flip: false
    use_rot: false
  val:
    name: HDRTV1K
    mode: LQGT_condition
    dataroot_LQ: ../dataset/Youtube_hdr/test_sdr
    dataroot_cond: ../dataset/Youtube_hdr/test_cond
    dataroot_GT: ../dataset/Youtube_hdr/test_hdr
    cond_scale: 4
    save_img: false
    testset: true

#### network structures
network_G:
  which_model_G: Ensemble_AGCM_LE
  classifier: color_condition
  cond_c: 6
  in_nc: 3
  out_nc: 3
  nf: 32
  act_type: 'relu'
  weighting_network: false

network_D:
  which_model_D: Discriminator_UNet
  input_nc: 3
  ndf: 64

#### path
path:
  root: ./
  pretrain_model_G: ../pretrained_models/Ensemble_AGCM_LE.pth
  strict_load: true
  # resume_state: 
  
  
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  TVloss_weight: 0 # !!float 1e-1

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
