#### general settings
name: local_enhancement
model: condition
use_tb_logger: true
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: HDRTV1K
    mode: LQGT_UNet_condition_dataset
    dataroot_LQ: ../dataset/training_set/AGCM_training_set_res_sub
    dataroot_GT: ../dataset/training_set/train_hdr_sub
    use_shuffle: true
    n_workers: 8
    batch_size: 8
    GT_size: 240
    use_flip: false
    use_rot: false
  val:
    name: HDRTV1K
    mode: LQGT_UNet_condition_dataset
    dataroot_LQ: ../dataset/test_set/AGCM_test_set_res
    dataroot_GT: ../dataset/test_set/test_hdr
    save_img: false
    condition: image
    mod: 8


#### network structures
network_G:
  which_model_G: HDRUNet3T1
  in_nc: 3
  out_nc: 3
  nf: 32
  act_type: relu
  weighting_network: false

#### path
path:
  root: ./
  # pretrain_model_G: 
  strict_load: false
  # resume_state: 

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4   
  lr_scheme: CosineAnnealingLR_Restart # MultiStepLR | CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 1000000
  warmup_iter: -1
  T_period: [400000, 200000, 200000, 200000]
  restarts: [400000, 600000, 800000, 1000000]
  eta_min: 1e-07
  restart_weights: [1, 0.5, 0.5, 0.5]
  pixel_criterion: l1
  pixel_weight: 1.0
  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
